// GENERATED by nice-generate-exports — do not edit by hand
// To update: edit package.exports.json and run `npm run generate-exports`

/** Flexible image component supporting img elements and background-image divs. */

export { default } from "./components/Image"
export * from "./components/Image"
export { getImageToken } from "./tokens"
export { registerVendorResolver } from "./services"
